apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-disc
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: periodic-disc
              image: rlpereirafct2002/periodic-disc:latest
          restartPolicy: OnFailure